version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: opendata
      POSTGRES_PASSWORD: akron
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
